version: "3.7"
services:
  backend:
    build: RestBase
    ports:
      - 8080:8080      
    restart: always
    secrets:
      - db-password
    environment:
      MYSQL_HOST: db
    networks:
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mysql:8.0.19
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
  
volumes:
  db-data: {}
secrets:
  db-password:
    file: RestBase/DBpassword.txt
networks:
  spring-mysql: {}